name: RespawnBlocks
version: '1.0'
main: me.afatcookie.respawnblocks.respawnblocks.RespawnBlocks
api-version: 1.19
authors: [ AFatCookie ]
description: Will "regenerate" blocks, rather than breaking it!
commands:
  rb:
    description: default command for RespawnBlocks
    permission: respawnblocks.admin
    permission-message: Insufficient Permission
